### ISSUE TITLE
Modify / remove wp media sizes

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/headless-wordpress#9]
Can we safely remove all WP media sizes and use the Glide images instead? Maybe only if we implement the Gutenberg API (#6).

**Comment by sboerrigter** [comment]
Can't we remove more media sizes now that we use our `<Image>` component? Or are they all used in the back-end?

**Comment by luukdv** [comment]
@sboerrigter All media sizes have been removed a while ago: https://github.com/trendwerk/headless-wordpress/blob/master/web/app/themes/headless/lib/admin.php#L50

You might still have some resized images from before that commit, but new uploaded ones will not have sizes generated.
